POST http://localhost:5500/transfer
http://192.168.99.100:5500/transfer
Content-Type: application/json

###

POST http://localhost:5500/transfer
Content-Type: application/json


  {
    "cardFromNumber": "4558445885584747",
    "cardFromValidTill": "08/23",
    "cardFromCVV": "351",
    "cardToNumber": "4558445885585555",
    "amount": {
      "value": 50000,
      "currency": "RUR"
    }
  }


###

POST http://localhost:5500/transfer
Content-Type: application/json

//Неправильный номер карты
{
  "cardFromNumber": "4558445885584746",
  "cardFromValidTill": "08/23",
  "cardFromCVV": "351",
  "cardToNumber": "4558445885585555",
  "amount": {
    "value": 50000,
    "currency": "RUR"
  }
}

###

POST http://localhost:5500/transfer
Content-Type: application/json

//Неправильный номер карты
{
  "cardFromNumber": "4558445885584747",
  "cardFromValidTill": "08/23",
  "cardFromCVV": "350",
  "cardToNumber": "4558445885585555",
  "amount": {
    "value": 50000,
    "currency": "RUR"
  }
}

###

POST http://localhost:5500/transfer
Content-Type: application/json

//Недостаточно средст на карте
{
  "cardFromNumber": "4558445885584747",
  "cardFromValidTill": "08/23",
  "cardFromCVV": "351",
  "cardToNumber": "4558445885585555",
  "amount": {
    "value": 50000000,
    "currency": "RUR"
  }
}
